# Generated by Django 4.2.13 on 2024-06-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('line_no', models.IntegerField(default=0)),
                ('picture_file_name', models.CharField(default='', max_length=100)),
                ('has_defect', models.BooleanField(default=False)),
                ('mh', models.IntegerField(default=0)),
                ('mb', models.IntegerField(default=0)),
                ('oc', models.IntegerField(default=0)),
                ('sh', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('spc', models.IntegerField(default=0)),
            ],
        ),
    ]
