# Generated by Django 4.2.13 on 2024-06-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_pcb_amount', models.IntegerField(default=0)),
                ('total_perfect_pcb_amount', models.IntegerField(default=0)),
                ('total_defective_pcb_amount', models.IntegerField(default=0)),
                ('line', models.IntegerField(default=0)),
                ('mh', models.IntegerField(default=[], verbose_name=models.IntegerField(default=0))),
                ('mb', models.IntegerField(default=[], verbose_name=models.IntegerField(default=0))),
                ('oc', models.IntegerField(default=[], verbose_name=models.IntegerField(default=0))),
                ('sh', models.IntegerField(default=[], verbose_name=models.IntegerField(default=0))),
                ('sp', models.IntegerField(default=[], verbose_name=models.IntegerField(default=0))),
                ('spc', models.IntegerField(default=[], verbose_name=models.IntegerField(default=0))),
            ],
        ),
    ]
