# Generated by Django 4.2.13 on 2024-06-12 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UserAdmin", "0005_remove_user_deviceuuid_user_empno"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "UUID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_assign", models.BooleanField(default=False)),
                ("is_finish", models.BooleanField(default=False)),
                (
                    "assign_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "finish_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "assign_worker",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAdmin.user",
                    ),
                ),
                (
                    "pcb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.pcb"
                    ),
                ),
            ],
        ),
    ]
