# Generated by Django 4.2.13 on 2024-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="UUID",
        ),
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
