# Generated by Django 4.2.13 on 2024-06-06 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "UUID",
                    models.UUIDField(
                        default=uuid.UUID("ba8c2c46-5db9-4e98-9b8c-ddb23fccb816"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=8)),
                ("password", models.CharField(max_length=50)),
                ("is_deleted", models.BooleanField(default=False)),
                ("role", models.CharField(default="worker", max_length=10)),
                ("full_name", models.CharField(default="", max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("deviceUUID", models.UUIDField()),
            ],
        ),
    ]
