# Generated by Django 4.2.13 on 2024-06-06 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="UUID",
            field=models.UUIDField(
                default=uuid.UUID("69a17a83-afba-4349-8df9-a764f348f8a8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
