# Generated by Django 4.2.13 on 2024-06-06 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0002_alter_user_uuid_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="UUID",
            field=models.UUIDField(
                default=uuid.UUID("d525b8d2-d437-4d47-b178-6ce9c553de1c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deviceUUID",
            field=models.UUIDField(null=True),
        ),
    ]
