# Generated by Django 4.2.13 on 2024-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0004_alter_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deviceUUID",
        ),
        migrations.AddField(
            model_name="user",
            name="empno",
            field=models.CharField(
                default="", editable=False, max_length=10, unique=True
            ),
        ),
    ]
